package:
  name: rpc_diism
  version: "0.2.0"

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - control
    - slycot
    - matplotlib
    - numpy
    - cvxpy

about:
  summary: "Template library for rpc_diism"
  license: "GPL-3.0-or-later"
